# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hyunjung <hyunjung@student.42seoul.kr>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/01/27 13:11:49 by devicii           #+#    #+#              #
#    Updated: 2022/02/23 16:22:09 by hyunjung         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# SRCS = 	ft_printf.c \
# 		ft_printf_char.c \
# 		ft_printf_nbr.c \
# 		ft_printf_nbrbase.c \
# 		ft_printf_ptr.c \
# 		ft_printf_str.c \
# 		ft_printf_unbr.c

# FLAGS = -c -Wall -Wextra -Werror
# AR_FLAGS = -rcs
# INCLUDE = -I./include

# OBJS = $(SRCS:.c=.o)

# $(NAME) : $(OBJS)
# 	ar $(AR_FLAGS) $(NAME) $(OBJS)

# all : $(NAME)

# clean :
# 	rm -f $(OBJS)

# fclean : clean
# 	rm -f $(NAME)

# re : fclean all

# .PHONY : all clean fclean re
